---
version: "3"
services:
  itoxidized:
    container_name: oxidized
    restart: always
    image: oxidized/oxidized:latest
    expose:
      - "8888"
    environment:
      - LC_ALL=en_US.UTF-8
      - CONFIG_RELOAD_INTERVAL=600
      - UPDATE_CA_CERTIFICATES=true
    volumes:
      - /etc/oxidized:/home/oxidized/.config/oxidized
      - /root/.ssh/id_rsa.crt:/usr/local/share/ca-certificates/MY-CA.crt
      - /root/.ssh/id_rsa:/root/.ssh/id_rsa
      - /root/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      - /etc/resolv.conf:/etc/resolv.conf
    networks:
      oxidized_network:
        ipv4_address: 172.30.1.3
    dns:
      - {use.your.internal.DNS}
    dns_search: {useyourinternalDNS.com}
    logging:
      options:
        max-size: 50m
  nginx:
    image: nginx-ldap
    container_name: nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/resolv.conf:/etc/resolv.conf
      - /etc/nginx/ssl/nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt
      - /etc/nginx/ssl/nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key
      - /etc/nginx/ssl/dhparam.pem:/etc/nginx/ssl/dhparam.pem
      - /etc/nginx/.htpasswd:/etc/nginx/.htpasswd
    networks:
      oxidized_network:
        ipv4_address: 172.30.1.2
    logging:
      options:
        max-size: 50m

networks:
  oxidized_network:
    driver: bridge
    ipam:
      driver: default
      config:
